const express = require('express');
const router = express.Router();
const RevenueSegment = require('../models/RevenueSegment');
const PriceList = require('../models/PriceList');
const Quote = require('../models/Quote');
const { protect } = require('../middleware/auth');
const { logAuditEvent } = require('../middleware/audit');

// In-memory array of generated reports history
const generatedReportsHistory = [
  { id: 'REP-101', name: 'Q3 2026 Executive Revenue & Margin Summary', format: 'PDF', generatedBy: 'Finance Controller', timestamp: '2026-09-08 14:30', status: 'Completed', fileSize: '2.4 MB' },
  { id: 'REP-102', name: 'Price Waterfall & Margin Leakage Audit', format: 'CSV', generatedBy: 'Pricing Manager', timestamp: '2026-09-09 09:15', status: 'Completed', fileSize: '850 KB' },
  { id: 'REP-103', name: 'Capacity Utilization & Transport Route Profitability', format: 'PDF', generatedBy: 'Executive', timestamp: '2026-09-10 11:20', status: 'Completed', fileSize: '3.1 MB' }
];

// @route GET /api/reports/history
router.get('/history', protect, async (req, res) => {
  res.json(generatedReportsHistory);
});

// @route GET /api/reports/waterfall
router.get('/waterfall', protect, async (req, res) => {
  try {
    // Price waterfall step calculation
    const listPriceTotal = 15000000;
    const standardVolumeDiscounts = 950000;
    const siblingPromotionalDiscounts = 620000;
    const financialAidSubsidies = 480000;
    const netBilledRevenue = listPriceTotal - standardVolumeDiscounts - siblingPromotionalDiscounts - financialAidSubsidies;
    const directCostBasis = 6200000;
    const netContributionMargin = netBilledRevenue - directCostBasis;

    res.json({
      waterfallSteps: [
        { stage: 'Gross List Price', value: listPriceTotal, type: 'base' },
        { stage: 'Volume Discounts', value: -standardVolumeDiscounts, type: 'leakage' },
        { stage: 'Sibling Promos', value: -siblingPromotionalDiscounts, type: 'leakage' },
        { stage: 'Financial Aid', value: -financialAidSubsidies, type: 'leakage' },
        { stage: 'Net Realized Revenue', value: netBilledRevenue, type: 'subtotal' },
        { stage: 'Direct Operating Costs', value: -directCostBasis, type: 'cost' },
        { stage: 'Net Contribution Margin', value: netContributionMargin, type: 'final' }
      ]
    });
  } catch (error) {
    console.error('Waterfall report error:', error);
    res.status(500).json({ error: 'Failed to generate waterfall report data' });
  }
});

// @route POST /api/reports/export
router.post('/export', protect, async (req, res) => {
  try {
    const { reportType, format, dateRange, campus } = req.body; // format: 'CSV' or 'PDF'

    const reportId = `REP-${Math.floor(100 + Math.random() * 900)}`;
    const reportName = `${reportType || 'Revenue & Profitability Report'} (${campus || 'All Campuses'})`;

    const newHistoryItem = {
      id: reportId,
      name: reportName,
      format: format || 'CSV',
      generatedBy: req.user.name,
      timestamp: new Date().toLocaleString(),
      status: 'Completed',
      fileSize: format === 'PDF' ? '1.8 MB' : '420 KB'
    };

    generatedReportsHistory.unshift(newHistoryItem);

    await logAuditEvent(req, 'EXPORT_REPORT', 'Report', reportId, `Exported ${reportName} in ${format} format`);

    if (format === 'CSV') {
      const csvData = `Report Title,${reportName}\nGenerated By,${req.user.name}\nDate,${new Date().toISOString()}\nSegment,Campus,Actual Revenue,Budget Revenue,Variance,Margin %\nTuition Fees,Oakridge Main,12450000,11800000,+650000,48%\nTransport,Oakridge Main,2850000,2900000,-50000,32%\nActivities,Oakridge Main,980000,900000,+80000,41%\nGrants,Oakridge Main,650000,650000,0,100%\nFacility,Oakridge Main,1120000,1000000,+120000,74%`;
      
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename="${reportId}_${reportType}.csv"`);
      return res.send(csvData);
    }

    res.json({
      message: `Report ${reportName} generated successfully!`,
      downloadUrl: `/api/reports/download/${reportId}`,
      reportDetails: newHistoryItem
    });
  } catch (error) {
    console.error('Export error:', error);
    res.status(500).json({ error: 'Failed to generate export file' });
  }
});

module.exports = router;
